#!/bin/sh
#cd /root/test_R
#cd /var/lib/jenkins/workspace/Deploy_BACK
sudo cp /var/lib/jenkins/workspace/Deploy_BACK/* /root/dev_jenk/
sudo cd /root/dev_jenk
git pull origin master     
#npm install       
pm2 restart all
